[features]
seeds = false
skip-lint = false
[programs.localnet]
puppet_cp_is = "F8BSgtDQA7gYxsaQyqBQoK3Q9W8ttNv5Y59QaB3tb7QZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/praky/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
